### ISSUE TITLE
Please provide more detailed instruction.

### ISSUE THREAD

**Issue by cycool29** [XinBow99/popdog_bot#1]
May I know what is **custom token path**? 
It is **not likely** to be a uuid from your example...

And also, can you provide **more detailed instruction** on how to configure the files?

**Comment by XinBow99** [comment]
1. Path is your flask router, you can put what you want. If you start on your server and up is 192.168.1.3. So u can create a bot session by 
"http://192.168.1.3/token_path/create/bot_name/bot_uuid"
Token path like a security rule. 
2. Ok wait for me. I will push new commit file.

Thanks for your asking.

**Comment by XinBow99** [comment]
@ITdairy Hey bro! I had provide more detailed instruction in the py file, and i rewrite readme.md.
Tomorrow I will write the readme in more detail! Please refer to the py file again!
Im appreciated for your reply.

**Comment by XinBow99** [comment]
> May I know what is **custom token path**?
> It is **not likely** to be a uuid from your example...
> 
> And also, can you provide **more detailed instruction** on how to configure the files?

**Comment by XinBow99** [comment]
@ITdairy  I had fix some bug in my code, and rewrite the readme.md!

**Comment by cycool29** [comment]
Thanks. Well is this normal? The PPS seem so slow.
![DeepinScreenshot_select-area_20210823092843](https://user-images.githubusercontent.com/88134003/130378073-a614fefe-e70d-42f4-923e-24e7e76f7690.png)

Can you mention what is the meaning of `Diff` `Avg` `PopdogRemainingTime` ? 

And also, should I put the same UUID between server-a and server-b?

**Comment by XinBow99** [comment]
About the picture you provided, that is not a good figures. It's below normal AVG should higher than 150. You can refer to the code and config to optimal and achieve the best figures of avg and diff.
Normally,You should set 
```
Python.
"clicks": random.randint(20000,1000000), 
to
random.randint(1000,2000), 

Config.
"PopDelay": 8,
```
and i have pushed a new commit, you can modify it on config.json 
"PopRange":{
        "Max": 200000000,
        "Min": 20000
    }
when you running the bot. It's replace "clicks": random.randint(20000,1000000),  to random.randint(min, max),
You can try the best parameter on the popdog.click. Plz observe the clicked/v2 api request status of network tab about Browser dev tools.
<img width="701" alt="截圖 2021-08-23 下午7 03 25" src="https://user-images.githubusercontent.com/36734430/130437074-3f331632-8417-40cc-8276-c06e26b889c9.png">
<img width="542" alt="截圖 2021-08-23 下午7 03 46" src="https://user-images.githubusercontent.com/36734430/130437111-b935bb43-70b9-4f68-a15f-35d83c770d6f.png">


- Diff 
That's "Difference between first and latest request of clicks value". For example, your first request clicks value is 2000 of Popdog database. So, we can assume x is first value 2000. The second of clicks value is 4000, third is 6000, 26000... etc. We assume that is x+1, x+2...x+n. So diff is x+n - x of clicks value. If current value is 166990 and first is 120990, we can calculate 166990 minus 120990 equal to diff.

- Avg 
Avg is diff divide by elapsed time. Assume diff is 46000clicks, elapsed time is 40s. We can calculate average clicks per second of 46000 clicks / 40s equal  to 1150 cps.

- Popdog remaining time
This is how long of request http://popdog.click/clicked/v2 RESTFul api spend between request and response.

- You don't need to put same uuid in server a and b. Just need put one server. And and this server will send uuid to another server, if this get error.

**Comment by cycool29** [comment]
Thanks for explanation. I clone the repo again and change the PopRange and BotStart Value and all runs very well yesterday with the 230-250 AVG . The only problem is it will decrease one x-ratelimit per request. This is not a big problem as when the x-ratelimit comes down to 1 it will pass the bot to another server. 

But at night when I check my server, the error occurs again :

![DeepinScreenshot_select-area_20210825084538](https://user-images.githubusercontent.com/88134003/130708074-bbbd6051-faf0-44b8-b547-3da2e545dbf8.png)

I think the UUID is being banned by popdog. However, the weird thing is the error still persists although I **changed the UUID**.

And another problem, when I start a bot:

![DeepinScreenshot_select-area_20210825085404](https://user-images.githubusercontent.com/88134003/130708650-8cd50990-2911-4051-bf70-201507d6f405.png)

Then it will send the bot to another server with the 1-5 pops per request...

![DeepinScreenshot_select-area_20210825085635](https://user-images.githubusercontent.com/88134003/130708804-dd946b83-9637-4f33-9ce8-065485b7830d.png)


Tried the following:
- changing UUID 
- clearing cookies in browser
- lower down the PopRange
- Clone again the repo 

All failed.

Did you face this problem when running your bot?


**ps: I don't know should I open a new issue, but I think commenting here is more convenient lol*

**Comment by XinBow99** [comment]
@ITdairy try set delay to 8

**Comment by XinBow99** [comment]
Maybe POPDOG's server change rule

**Comment by cycool29** [comment]
> @ITdairy try set delay to 8

U mean PopDelay in config.json?
I am keeping the default value which is 8.
